apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cost-demo-scaler
spec:
  scaleTargetRef:
    name: cost-demo
  minReplicaCount: 0
  maxReplicaCount: 4
  cooldownPeriod: 300
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: 0 9 * * 1-5
        end: 0 19 * * 1-5
        desiredReplicas: "1"
